### PR TITLE
Json api rc3

### PR DESCRIPTION
**Pull request by bmac**
This uses the work from this pr https://github.com/emberjs/data/pull/2904 to implement JSON API rc3. Any bugs we find in the `json-api-*` files should be upstreamed to Ember Data.

cc @bobholt @tkellen @leobalter

### CODE REVIEW

**Comment by leobalter** [comment]
seems very interesting. I'll try to manually get this code and test against my app. Meanwhile, is there anyway to set proper tests to it?

**Comment by bmac** [comment]
Yeah, thats on my list of things to do. Most of the `json-api-*` code is already tested in the Ember Data pr so I'd prefer not to duplicate that work. However, things like the underscoring `keyForAttribute` and `keyForRelationship` should be tested in this repo.

**Comment by leobalter** [comment]
rad!

**Comment by bobholt** [comment]
Excited that I may not have to do anything! I'll try to put this into Away today. I just have to remember how to ember.

**Pull request merged**
